#!/usr/bin/env python3
# Copyright (c) 2025 FLEXT Team. All rights reserved.
"""AI Hub governance hook projection: gemini beforeagent."""
from __future__ import annotations

import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
    ('{"hookSpecificOutput":{"hookEventName":"BeforeAgent","additional'
         'Context":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:5888ee9f8147f6'
         '3364a4f7cd6906e9d837f58cb8a8546844760c526ecb1a303b -->\\n# Gener'
         'ated session governance capsule\\n\\nThis projection is derived '
         'by `agentsctl sync`; edit canonical `AGENTS.md`, `rules/`, `skil'
         'ls/`, or `commands/`, never this output. The operator\'s newest '
         'request has precedence. Provider hooks are delivery mechanisms, '
         'not policy owners.\\n\\n## Rule `architecture/engineering-core`\\'
         'n\\n# Engineering core\\n\\nFor every implementation:\\n\\n1. Re'
         'search repository owners, dependencies, and canonical documentat'
         'ion.\\n2. Remove scope without a current requirement or consumer'
         ' (YAGNI).\\n3. Elect one writable authority; every other copy is'
         ' a generated projection\\n   (SSOT).\\n4. Apply SOLID only to a '
         'responsibility or dependency boundary under change.\\n5. Impleme'
         'nt through the owner and simplify without weakening behavior.\\n'
         '6. Remove duplication and god components; recheck YAGNI, SSOT, S'
         'OLID.\\n7. Exercise runtime behavior, run every applicable nativ'
         'e gate, and complete\\n   the approved landing cycle before chan'
         'ging phase.\\n\\nAt a cross-boundary failure, prove the producer'
         ' contract and output. Fix its\\nowner when invalid or the receiv'
         'er when it conforms. Never alter a correct\\nadjacent owner for '
         'an invalid consumer; symptom workarounds are defects.\\n\\nHardc'
         'odes, normalized failure, failover, retry, fallback, compatibili'
         'ty,\\npartial execution, keyring, and unevidenced success are de'
         'fects. Typed owners\\nkeep defaults. The first exception escapes'
         ' its CLI with traceback and cause.\\n\\nGit, runtime, build, and'
         ' tests are baseline. Auxiliary tracking is a capability.\\nAuxil'
         'iary capabilities apply only when authorized and selected; insta'
         'llation\\nnever selects. Do not load, probe, or gate dormant cap'
         'abilities. Invalid\\nselected authorization, configuration, read'
         'iness, or result fails without\\nfallback. Require only non-deri'
         'vable values.\\n\\nAn external token validation without its toke'
         'n is not executed and is recorded\\nas `NOT EXECUTED`, never gre'
         'en; it does not block offline gates, landing, or\\npost-merge pr'
         'oof. Direct invocation selects it: the token becomes required an'
         'd\\nany failure escapes without skip, catch, fallback, or normal'
         'ization.\\n\\nCompose with `generalized ownership` (rule file),\\'
         'n`strict execution` (rule file),\\n`runtime evidence` (rule file'
         '),\\n`storage isolation` (rule file),\\n`security closure` (rule'
         ' file).\\n\\n## Rule `coordination/operator-precedence`\\n\\n# N'
         'ewest operator instruction wins; adjust artifacts to it\\n\\nAut'
         'hority order: operator request > declared orchestration contract'
         ' > canonical\\ntracker > ADRs > skills > docs, and newest supers'
         'edes oldest. On conflict,\\nadjust the lower or older artifact t'
         'o match; never override the operator to\\nsatisfy stale guidance'
         '.\\n\\nWhile orchestration and tracker runtimes are suspended, d'
         'o not invoke them.\\nCreate no substitute tracker or ledger, pre'
         'serve implementation evidence only\\nin separately authorized Gi'
         't/PR/CI, and leave phase closure open.\\n\\nExact operator autho'
         'rization naming targets, disposition, recovery, and\\nvalidation'
         ' survives interruption, divergence, and red gates; re-preflight '
         'and\\ncontinue. Ask only when the effect expands beyond it or tw'
         'o evidenced current\\nintentions conflict. State alone proves no'
         ' intention, actor, or process.\\n\\n## Rule `ethics/professional'
         '-integrity`\\n\\n# Professional integrity is absolute\\n\\nNever'
         ' lie, fabricate evidence, hide a blocker, bypass a gate, or patc'
         'h a symptom\\nonly to make a check pass. Fix the generalized roo'
         't cause with full context and\\nreport exact command, working di'
         'rectory, exit code and decisive output.\\n\\n## Rule `runtime/st'
         'rict-execution`\\n\\n# Strict execution is universal and non-opt'
         'ional\\n\\nEvery project and projected agent applies all of thes'
         'e policies together:\\n\\n- `fail loud` (rule file);\\n- `no fal'
         'lback` (rule file);\\n- `preflight before effects` (rule file);\\'
         'n- `required environment` (rule file);\\n- `atomic effects` (rul'
         'e file);\\n- `causal subprocess propagation` (rule file);\\n- `n'
         'o keyring` (rule file);\\n- `zero residue` (rule file).\\n\\nThe'
         ' policies are cumulative. A project rule may make them narrower '
         'or reject\\nmore inputs; it cannot relax, catch, normalize, skip'
         ', defer, or route around any\\nof them. Existing opposing behavi'
         'or is a blocking violation to exterminate at\\nits owner, never '
         'grandfathered compatibility.\\n\\nResolve gate applicability bef'
         'ore invocation. A dormant external-token gate is\\nnot executed;'
         ' selecting or invoking it applies every policy above.\\n\\n## Ca'
         'pability indexes\\n\\nSkills: caveman, context-canary, fix-forwa'
         'rd-collaboration, governance-audit, operator-correction-learning'
         ', plan-focus-recovery, sprint-closure, strategic-compact, verifi'
         'cation-loop\\nCommands: add-language-rules, database-migration, '
         'feature-development, ghi-list, pr-list, ralph-loop, security-tri'
         'age, synthesize-governance\\n"}}'),

)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
